main:
- name: Biography
  url: /#bio
  weight: 10
- name: Research
  url: /#research
  weight: 20
- name: Publications
  url: /#papers
  weight: 30
- name: Projects
  url: projects/
  weight: 40
- name: Teaching
  url: courses/
  weight: 50
- name: Talks
  url: /#talks
  weight: 60
- name: Notes
  url: /#news
  weight: 70
- name: Experience
  url: experience/
  weight: 80
